version: '2'
services:
    telefonia-app:
        image: telefonia
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://telefonia-postgresql:5432/telefonia
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    telefonia-postgresql:
        extends:
            file: postgresql.yml
            service: telefonia-postgresql
